[ci skip] Pushing chaincode installation files
Signed-off-by: Anjalikarhana <anjalikarhana99@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
@@ -141,15 +141,43 @@ spec:
         - |-
           #!/bin/bash sh
 
+          # Function to check the installed Go version
+          check_go_version() {
+          installed_version=$(go version | awk '{print $3}')
+          required_version="1.16"
+    
+          if [[ "$installed_version" < "$required_version" ]]; then
+           echo "Installed Go version is $installed_version, which is older than $required_version."
+           return 1
+          else
+          echo "Installed Go version is up to date."
+          return 0
+           fi
+          }
+
+          # Download and install Go 1.16 if necessary
+          if ! check_go_version; then
+          echo "Downloading and installing Go 1.16..."
+    
           # Download Go 1.16 binary distribution
           curl -LO https://golang.org/dl/go1.16.linux-amd64.tar.gz
-
+    
           # Extract the downloaded archive
           tar -C /usr/local -xzf go1.16.linux-amd64.tar.gz
-
+    
           # Remove the downloaded archive
           rm go1.16.linux-amd64.tar.gz
-          ## Git repository clone for chaincode
+    
+          echo "Go 1.16 installed successfully."
+          else
+          echo "Go version is up to date, no need to install."
+          fi
+
+          # Ensure Go version is 1.16 or higher before proceeding
+          if ! check_go_version; then
+           echo "ERROR: Unable to update Go version to 1.16 or higher. Exiting."
+           exit 1
+          fi
 
           
           # Set GOPATH
