[ci skip] Pushing chaincode installation files
Signed-off-by: Anjalikarhana <anjalikarhana99@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
@@ -147,6 +147,10 @@ spec:
           packages_to_install="curl openssh"
           install_packages "$packages_to_install"
 
+          
+
+          # Create symbolic link for libc.musl-x86_64.so.1
+          mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
 
 
 
@@ -169,6 +173,17 @@ spec:
           fi
          
          
+          # Download and extract Go 1.20
+          if wget -c https://dl.google.com/go/go1.20.linux-amd64.tar.gz -O - |  tar -xz -C /root ; then
+              echo "Go 1.20 downloaded and extracted successfully."
+              # Set up environment variables
+              export PATH=$PATH:$GOPATH/bin
+
+  
+          else
+            echo "Failed to download or extract Go 1.13. Exiting..."
+            exit 1
+          fi
 
           if [ "${CC_RUNTIME_LANGUAGE}" = "golang" ]; then
              ## Copying desired chaincode to a location relative to $GOPATH/src
