[ci skip] Pushing Peer files
Signed-off-by: Anjalikarhana <anjalikarhana99@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode5.yaml b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode5.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode5.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode5.yaml
@@ -69,7 +69,7 @@ spec:
         - name: MOUNT_PATH
           value: /secret
         - name: NETWORK_VERSION
-          value: "{{ $.Values.metadata.network.version }}"
+          value: "2.2.2"
         - name: VAULT_TYPE
           value: "{{ $.Values.vault.type }}"
         command: ["sh", "-c"]
@@ -139,130 +139,56 @@ spec:
         command: ["sh", "-c"]
         args:
         - |-
-          #!/bin/bash sh
+          #!/bin/bash sh 
 
           . /scripts/package-manager.sh
+           
+          # Define the packages to install
+          packages_to_install="curl openssh"
+          install_packages "$packages_to_install"
 
-          ## Git repository clone for chaincode
-          version2_5=`echo $NETWORK_VERSION | grep -c 2.5`
-          if [ $version2_5 = 1 ]
-          then
-            GOPATH="/root/go"
-            mkdir -p $GOPATH 
-            # Define the packages to install
-            packages_to_install="openssh-client git"
-            install_packages "$packages_to_install"
-          else 
-            # Define the packages to install
-            packages_to_install="curl openssh"
-            install_packages "$packages_to_install"
-          fi 
 
+
+          #download fabric
+          GOPATH="/root/go"
+          mkdir -p $GOPATH/src/github.com/hyperledger
+          cd $GOPATH/src/github.com/hyperledger
+          git clone -b release-1.2 https://github.com/hyperledger/fabric.git
+
+          # Create directory
           mkdir -p /root/.ssh/     
           ssh-keyscan {{ $.Values.chaincode.repository.hostname }} > /root/.ssh/known_hosts
           git_password=$(cat /opt/gopath/src/github.com/hyperledger/fabric/crypto/user_cred)
           cd /tmp && git clone https://{{ $.Values.chaincode.repository.git_username }}:$git_password@{{ $.Values.chaincode.repository.url }} -b {{ $.Values.chaincode.repository.branch }} chaincode > git.log 2>&1
+
           ## Check if the repository was cloned correctly
-          if [ $? -ne 0 ];
-          then
-            cat git.log
-            exit 1
+          if [ $? -ne 0 ]; then
+              cat git.log
+              exit 1
           fi
-          ls
-          echo $GOPATH
-          if [ ${CC_RUNTIME_LANGUAGE} = "golang" ]
-          then
-            ## Copying desired chaincode to a location relative to $GOPATH/src
-            mkdir -p $GOPATH/src/github.com/chaincode
-            cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
 
-            # Get dependencies
-            mkdir -p $GOPATH/bin && curl https://raw.githubusercontent.com/hyperledger/bevel/main/platforms/hyperledger-fabric/scripts/install.sh | sh
-            if [ $version2_5 = 1 ]
-            then
-              export PATH=$PATH:$GOPATH/bin
-              go env -w GO111MODULE=auto
-            fi
-            cd $GOPATH/src/github.com/chaincode && dep ensure
 
-            #chaincode path
-            CC_SRC_PATH="github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}"
 
-            if ! [ -d "vendor" ];then
-              GO111MODULE=on go mod vendor
-              CC_SRC_PATH="${PWD}"
-            fi
+          if [ "${CC_RUNTIME_LANGUAGE}" = "golang" ]; then
+             ## Copying desired chaincode to a location relative to $GOPATH/src
+             go env GOPROXY=https://goproxy.io,direct
+             go env GO111MODULE=on
+             mkdir -p $GOPATH/src/github.com/chaincode
+             cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
+             cd $GOPATH/src/github.com/chaincode/supplychain/cmd
 
-          elif [ ${CC_RUNTIME_LANGUAGE} = "java" ]
-          then
-            ## Copying desired chaincode to a location 
-            mkdir -p $GOPATH/src/github.com/chaincode
-            cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
+             # Get dependencies
+             mkdir -p $GOPATH/bin && curl https://raw.githubusercontent.com/hyperledger/bevel/main/platforms/hyperledger-fabric/scripts/install.sh | sh
+             export PATH=$PATH:$GOPATH/bin
+             go env -w GO111MODULE=auto
+             cd $GOPATH/src/github.com/chaincode/supplychain/cmd && dep init && dep ensure
 
-            # Get dependencies: Define the packages to install
-            packages_to_install="openjdk8"
-            install_packages "$packages_to_install"
 
-            java -version
-
-            # Define the packages to install
-            packages_to_install="gradle"
-            install_packages "$packages_to_install"
-
-            gradle -v
-            cd $GOPATH/src/github.com/chaincode && dep ensure
-
-            CC_SRC_PATH="/$GOPATH/src/github.com/chaincode/"
-
-            echo "CC_SRC_PATH= $CC_SRC_PATH"
-            current_path=`pwd`
-            echo $current_path
-
-            echo "Compiling Java code..."
-            chmod +x gradlew
-            ./gradlew installDist --stacktrace
-            cd $current_path
-            echo "Finished compiling Java code"
-
-            #chaincode path
-            CC_SRC_PATH=$CC_SRC_PATH/build/install/${CHAINCODE_NAME}
-
-            echo $CC_SRC_PATH
-          elif [ ${CC_RUNTIME_LANGUAGE} = "node" ]
-          then
-            ## Copying desired chaincode to a location relative to $GOPATH/src
-            mkdir -p $GOPATH/src/github.com/chaincode
-            cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
-
-            #chaincode path
-            CC_SRC_PATH="${GOPATH}/src/github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}"
+             #chaincode path
+             CC_SRC_PATH="$GOPATH/src/github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}"
           fi
-          version1_4=`echo $NETWORK_VERSION | grep -c 1.4`
-          if [ $version1_4 = 1 ];then
 
-            ## Checking installed chaincode
-            INSTALLED=$(peer chaincode list --installed | grep "Name: ${CHAINCODE_NAME}, Version: ${CHAINCODE_VERSION},")
-            if [ -n "${INSTALLED}" ]
-            then
-              echo "chaincode ${CHAINCODE_NAME} version ${CHAINCODE_VERSION} is installed, skipping... "
-              exit 0
-            fi
-
-            echo "Installing Chaincode for ${NETWORK_VERSION}"
-            ## Installing chaincode on a peer
-            peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p ${CC_SRC_PATH} --lang ${CC_RUNTIME_LANGUAGE}
-            echo "Chaincode installed for Fabric v.1.4.X"         
-          else
-            ## Checking installed chaincode
-            INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | \
-              jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
-            if [ -n "${INSTALLED}" ]
-            then
-              echo "chaincode ${CHAINCODE_NAME}_${CHAINCODE_VERSION} is installed, skipping... "
-              exit 0
-            fi
-
-            echo "Installing Chaincode for ${NETWORK_VERSION}"
+           echo "Installing Chaincode for ${NETWORK_VERSION}"
             if [ $PEER_NAME = "peer0" ];then
               ## packaging chaincode
               echo "Packaging chaincode for the first peer"
@@ -278,22 +204,28 @@ spec:
               export CHAINCODE_NAME=${PACKAGE_ID}
               echo "installing ${CHAINCODE_NAME} on ${CORE_PEER_ADDRESS}"
             fi
-            ## Installing Chaincode
-            peer lifecycle chaincode install ${CHAINCODE_NAME}.tar.gz
-            echo "Chaincode installed for Fabric v.2.X"
-            ## Check if chaincode got installed 
-            INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | \
-              jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
-            if ! [ -n "${INSTALLED}" ]
+
+          ## Installing Chaincode
+          peer lifecycle chaincode install ${CHAINCODE_NAME}.tar.gz
+          echo "Chaincode installed for Fabric v.2.X"
+          ## Check if chaincode got installed 
+          INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | \
+            jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
+          if ! [ -n "${INSTALLED}" ]
             then
-              echo "Error while installing chaincode, exiting.."
+              echo "Error while installing chaincode, exiting.. ${INSTALLED}"
               exit 1
             fi
-          fi
+          fi  
 
           #query installed
           echo "peer query installed"
           peer lifecycle chaincode queryinstalled
+
+          #query installed
+          echo "peer query installed"
+          peer lifecycle chaincode queryinstalled
+
         env:
         - name: PEER_NAME
           value: {{ $.Values.peer.name }}
