[ci skip] Pushing chaincode installation files
Signed-off-by: Anjalikarhana <anjalikarhana99@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
@@ -144,11 +144,10 @@ spec:
           . /scripts/package-manager.sh
            
           # Define the packages to install
-          packages_to_install="curl openssh build-essential"
+          packages_to_install="curl openssh"
           install_packages "$packages_to_install"
 
-          #check os version
-          uname -a
+
           # #remove go version 1.14
           # rm -rvf /usr/local/go
           
@@ -165,21 +164,25 @@ spec:
               exit 1
           fi
          
-          #echo "installing go version 1.10.3..." 
-          apk add --no-cache --virtual build-essential .build-deps bash gcc musl-dev openssl go 
+          ls
 
           # Download and extract Go 1.17
-          wget -O go.tgz  https://dl.google.com/go/go1.17.linux-amd64.tar.gz 
-          tar -C /usr/local -xzf go.tgz 
-          #changing directory
-          cd /usr/local/go/src/ && ./make.bash 
-          cat bash
-          export PATH="/usr/local/go/bin:$PATH"
-          export GOPATH="/opt/go/" 
-          export PATH=$PATH:$GOPATH/bin 
-          apk del .build-deps 
-          echo "go version: $(go version)"
-          
+          if wget -c https://dl.google.com/go/go1.17.linux-amd64.tar.gz -O - |  tar -xz -C /usr/local ; then
+              echo "Go 1.17 downloaded and extracted successfully."
+              # Set up environment variables
+              export GOROOT=$(go1.17 env GOROOT)
+              export PATH=${GOROOT}/bin;${PATH}
+              # mkdir -p $GOPATH/bin
+              # export PATH=$PATH:/usr/local/go/bin
+              # echo "GOROOT set to: $GOROOT"
+              # echo "GOPATH set to: $GOPATH"
+              echo "PATH set to: $PATH"
+              echo "go version: $(go version )"
+              echo "Go environment variables set up successfully."
+          else
+            echo "Failed to download or extract Go 1.17. Exiting..."
+            exit 1
+          fi
 
           if [ "${CC_RUNTIME_LANGUAGE}" = "golang" ]; then
              ## Copying desired chaincode to a location relative to $GOPATH/src
