[ci skip] Pushing chaincode installation files
Signed-off-by: Anjalikarhana <anjalikarhana99@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
@@ -148,6 +148,10 @@ spec:
           GOPATH="/root/go"
           mkdir -p $GOPATH 
 
+          # Check Go version
+          go_version=$(go version)
+          echo "Go version: $go_version"
+
           # Define the packages to install
           packages_to_install="openssh-client git"
           install_packages "$packages_to_install"
@@ -158,9 +162,14 @@ spec:
           cd /tmp && git clone https://{{ $.Values.chaincode.repository.git_username }}:$git_password@{{ $.Values.chaincode.repository.url }} -b {{ $.Values.chaincode.repository.branch }} chaincode > git.log 2>&1
 
           ## Check if the repository was cloned correctly
-          if [ $? -ne 0 ]; then
-              cat git.log
-              exit 1
+          # if [ $? -ne 0 ]; then
+          #     cat git.log
+          #     exit 1
+          # fi
+          if [ $? -eq 0 ]; then
+             echo "Chaincode cloning successful"
+          else
+              echo "Error: Chaincode cloning failed"
           fi
 
           ls
@@ -170,7 +179,7 @@ spec:
           ## Copying desired chaincode to a location relative to $GOPATH/src
           mkdir -p $GOPATH/src/github.com/chaincode
           cp -R /tmp/chaincode/{{ $.Values.chaincode.repository.path }}/* $GOPATH/src/github.com/chaincode/
-
+          cd $GOPATH/src/github.com/chaincode/ && ls
           # Get dependencies
           if [ -d "vendor" ]; then
              rm -rf vendor # Remove existing vendor directory
@@ -179,20 +188,41 @@ spec:
           go mod vendor
 
           #chaincode path
+          ls $GOPATH/src/github.com/chaincode/
+
           CC_SRC_PATH="github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}"
-           fi
-           ## Installing Chaincode
-           peer lifecycle chaincode install ${CHAINCODE_NAME}.tar.gz
-           echo "Chaincode installed for Fabric v.2.X"
-           ## Check if chaincode got installed 
-           INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | \
-             jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
-           if ! [ -n "${INSTALLED}" ]
-           then
-             echo "Error while installing chaincode, exiting.."
-             exit 1
-           fi
+           echo "Installing Chaincode for ${NETWORK_VERSION}"
+            if [ $PEER_NAME = "peer0" ];then
+              ## packaging chaincode
+              echo "Packaging chaincode for the first peer"
+              peer lifecycle chaincode package ${CHAINCODE_NAME}.tar.gz --path ${CC_SRC_PATH} --lang ${CC_RUNTIME_LANGUAGE} --label ${CHAINCODE_NAME}_${CHAINCODE_VERSION}
+            else
+              export CORE_PEER_ADDRESS=${PEER0_ADDRESS}
+              echo "Extracting package id"
+              peer lifecycle chaincode queryinstalled > log.txt
+              PACKAGE_ID=$(cat log.txt | grep "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" | sed -n "/${CC_NAME}_${CC_VERSION}/{s/^Package ID: //; s/, Label:.*$//; p;}")
+              echo "Package Id Extracted ${PACKAGE_ID}"
+              peer lifecycle chaincode getinstalledpackage --package-id ${PACKAGE_ID}
+              export CORE_PEER_ADDRESS=${PEER_ADDRESS}
+              export CHAINCODE_NAME=${PACKAGE_ID}
+              echo "installing ${CHAINCODE_NAME} on ${CORE_PEER_ADDRESS}"
+            fi
+            ## Installing Chaincode
+            peer lifecycle chaincode install ${CHAINCODE_NAME}.tar.gz
+            echo "Chaincode installed for Fabric v.2.X"
+            ## Check if chaincode got installed 
+            INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | \
+              jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
+            if ! [ -n "${INSTALLED}" ]
+            then
+              echo "Error while installing chaincode, exiting.."
+              exit 1
+            fi
           fi
+
+          #query installed
+          echo "peer query installed"
+          peer lifecycle chaincode queryinstalled
 
           #query installed
           echo "peer query installed"
