[ci skip] Pushing chaincode installation files
Signed-off-by: Anjalikarhana <anjalikarhana99@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
@@ -146,10 +146,23 @@ spec:
           # Define the packages to install
           packages_to_install="curl openssh"
           install_packages "$packages_to_install"
-        
-          #creating go directory
+
+          
+
+           #remove go version 1.14
+           rm -rf /usr/local/go
+          
+
+          # Create symbolic link for libc.musl-x86_64.so.1
+          mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
+
+
+
+          #download fabric
           GOPATH="/root/go"
-          mkdir -p $GOPATH 
+          mkdir -p $GOPATH/src/github.com/hyperledger
+          cd $GOPATH/src/github.com/hyperledger
+          git clone -b release-1.2 https://github.com/hyperledger/fabric.git
 
           # Create directory
           mkdir -p /root/.ssh/     
@@ -162,7 +175,19 @@ spec:
               cat git.log
               exit 1
           fi
-        
+         
+         
+          # Download and extract Go 1.17
+          if wget -c https://dl.google.com/go/go1.17.linux-amd64.tar.gz -O - |  tar -xz -C /root ; then
+              echo "Go 1.17 downloaded and extracted successfully."
+              # Set up environment variables
+              export PATH=$PATH:$GOPATH/bin
+
+  
+          else
+            echo "Failed to download or extract Go 1.13. Exiting..."
+            exit 1
+          fi
 
           if [ "${CC_RUNTIME_LANGUAGE}" = "golang" ]; then
              ## Copying desired chaincode to a location relative to $GOPATH/src
@@ -172,10 +197,12 @@ spec:
              cd $GOPATH/src/github.com/chaincode/
              go mod init github.com/chaincode
 
-             go mod tidy
 
             # Check if the vendor directory exists
             if [ ! -d vendor ]; then
+
+              # Tidy up module dependencies
+              go mod tidy 
 
               # Vendor dependencies
               GO111MODULE=on go mod vendor
