[ci skip] Pushing chaincode installation files
Signed-off-by: Anjalikarhana <anjalikarhana99@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-chaincode-install/templates/install_chaincode.yaml
@@ -160,17 +160,14 @@ spec:
 
           mkdir -p /root/.ssh/     
           ssh-keyscan {{ $.Values.chaincode.repository.hostname }} > /root/.ssh/known_hosts
-          git_password=$(cat /opt/gopath/src/github.com/hyperledger/fabric/crypto/user_cred)         
-          cd /tmp &&
-          git config --global http.postBuffer 157286400 &&
-          git config --global core.compression 0 &&
-          git config --global core.autocrlf false &&
-          git config --global http.version HTTP/1.1  && git clone https://{{ $.Values.chaincode.repository.git_username }}:$git_password@{{ $.Values.chaincode.repository.url }} -b {{ $.Values.chaincode.repository.branch }} chaincode > /tmp/git.log 2>&1
+          git_password=$(cat /opt/gopath/src/github.com/hyperledger/fabric/crypto/user_cred)
+          cd /tmp && git config --global core.compression 0 &&  git config --global core.autocrlf false && git config --global http.version HTTP/1.1 && git config --global http.postBuffer 157286400  && git clone https://{{ $.Values.chaincode.repository.git_username }}:$git_password@{{ $.Values.chaincode.repository.url }} -b {{ $.Values.chaincode.repository.branch }} chaincode > git.log 2>&1
           ## Check if the repository was cloned correctly
-          if [ $? -ne 0 ]; then
-             cat /tmp/git.log
+          if [ $? -ne 0 ];
+          then
+            cat git.log
             exit 1
-          fi 
+          fi
           ls
           echo $GOPATH
           if [ ${CC_RUNTIME_LANGUAGE} = "golang" ]
@@ -289,7 +286,7 @@ spec:
               jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
             if ! [ -n "${INSTALLED}" ]
             then
-              echo "Error while installing chaincode, exiting.. ${INSTALLED}"
+              echo "Error while installing chaincode, exiting.."
               exit 1
             fi
           fi
